### ISSUE TITLE
Can't register in client init when updating to 1.16

### ISSUE THREAD

**Issue by supersaiyansubtlety** [CottonMC/LibGui#67]
**Describe the bug**
After following the [Getting Started with GUIs](https://github.com/CottonMC/LibGui/wiki/Getting-Started-with-GUIs) portion of the wiki to update my 1.15 mod to 1.16, I get the following error:
```
incompatible types: cannot infer type-variable(s) H,S
        ScreenRegistry.register(AutomatedCraftingInit.AUTO_CRAFTER_SCREEN_HANDLER_TYPE, (gui, player, title) -> new AutoCrafterScreen(gui, player, title));
```

**To Reproduce**
Follow the tutorial on the above wiki page, try to build

**Screenshots** *Optional*
![Lambda Function](https://user-images.githubusercontent.com/618276/85932126-225afd80-b87e-11ea-8e58-72f146b83cae.png)

**Version of the (please complete the following information):**
```
	fabric_api_version = 0.13.1+build.370-1.16
	fabricloader = >=0.7.4

	libgui_version = 2.0.1+1.16.1
	autoconfig1u_version = 3.2.0-unstable
	cloth_config_2_version = 4.5.6
```

[Here](https://gitlab.com/supersaiyansubtlety/automated_crafting/-/commit/252f140151d5ed95075787fdc13f8f6f481ac533) is the commit containing my attempt to update my mod to 1.16. 

[Here](https://gitlab.com/supersaiyansubtlety/automated_crafting/-/blob/master/src/main/java/net/sssubtlety/automated_crafting/AutomatedCraftingClientInit.java) is my clientInit class. 

Apologies if this is just an error on my part, but I've been unable to either find any discrepancies between my mod and the wiki or get any help on the fabric discord for a couple days now.

**Comment by Juuxel** [comment]
This seems to be javac acting dumb with generics and lambdas again; try specifying the generics to `ScreenRegistry.register` manually.

**Comment by supersaiyansubtlety** [comment]
Specifying types gives this:
```
error: method register in class ScreenRegistry cannot be applied to given types;
        ScreenRegistry.register(AutomatedCraftingInit.AUTO_CRAFTER_SCREEN_HANDLER_TYPE, (AutoCrafterGuiDescription gui, PlayerEntity player, Text title) -> new AutoCrafterScreen(gui, player, title));
                      ^
  required: ScreenHandlerType<? extends H>,Factory<? super H,? extends S>
  found: ScreenHandlerType,(AutoCraft[...]itle)
  reason: cannot infer type-variable(s) H,S
```
![Lambda Function With Types](https://user-images.githubusercontent.com/618276/85934698-9ce64600-b89b-11ea-871d-f7e2b36bef6c.png)

Looks like I need to extend something I haven't? Still can't see anything I missed from the wiki though.

**Comment by Juuxel** [comment]
The second parameter to the [`Factory`](https://github.com/FabricMC/fabric/blob/dfd0b839f4ea14da86c0ac92db3f60a6128d1a30/fabric-screen-handler-api-v1/src/main/java/net/fabricmc/fabric/api/client/screenhandler/v1/ScreenRegistry.java#L85) lambda is a `PlayerInventory`, not a `PlayerEntity`. Also, you might have to specify generics manually to the `ScreenRegistry.register` *call* itself, such as in [the screen handler API's test mod](https://github.com/FabricMC/fabric/blob/dfd0b839f4ea14da86c0ac92db3f60a6128d1a30/fabric-screen-handler-api-v1/src/testmod/java/net/fabricmc/fabric/test/screenhandler/client/ClientScreenHandlerTest.java#L31).

**Comment by supersaiyansubtlety** [comment]
Ok, but the Screen class takes a `PlayerEntity`, not a `PlayerInventory` according to the wiki. 
![Constructor Type Miss-match](https://user-images.githubusercontent.com/618276/85958595-7849a700-b94b-11ea-9fc3-f09a92481463.png)

**Comment by supersaiyansubtlety** [comment]
I'm also confused on what my implementation of `createScreenHandlerFactory` in my `BlockEntity` should contain. 
The '[Required Interfaces](https://github.com/CottonMC/LibGui/wiki/Getting-Started-with-GUIs#required-interfaces)' is the portion of the wiki I'm confused about:
```
NamedScreenHandlerFactory on the BlockEntity
- An implementation of Block.createScreenHandlerFactory for accessing the block entity. Vanilla's BlockWithEntity implements this for you if you extend it.
```
This is my incomplete attempt:
```
@Override
protected ScreenHandler createScreenHandler(int syncId, PlayerInventory playerInventory) {
    BlockState state = this.world.getBlockState(pos);
    NamedScreenHandlerFactory factory = state.getBlock().createScreenHandlerFactory(state, world, pos);
    if(factory != null) {
        return factory.createMenu(syncId, playerInventory, );
    } else {
        throw new IllegalStateException("AutoCrafterBlockEntity's createScreenHandlercould not create factory. ");
    }
}
```

**Comment by Juuxel** [comment]
Uh yeah, my bad about that entity vs inventory confusion. That's fixed in the wiki now.

The implementation of `NamedScreenHandlerFactory.createMenu` in the block entity class should only create the `SyncedGuiDescription` object.

The block entity is then used in `Block.createScreenHandlerFactory` which is implemented in `BlockWithEntity` subclasses (you can also override that yourself if you extend another block class).

**Comment by Juuxel** [comment]
The [Implement `NamedScreenHandlerFactory` on your BlockEntity](https://github.com/CottonMC/LibGui/wiki/Getting-Started-with-GUIs#implement-namedscreenhandlerfactory-on-your-blockentity) section of the wiki article is also useful here.

**Comment by supersaiyansubtlety** [comment]
Ah, that `inventory.player` makes more sense, thanks. 

I'm not sure how I need to specify the generics for `ScreenRegistry.register` because I don't have my own screen handler class. I tried my GuiDescription and the game launched, but I got a stack overflow when I right-clicked my block. 
```
        ScreenRegistry.<AutoCrafterGuiDescription, AutoCrafterScreen>register(AutomatedCraftingInit.AUTO_CRAFTER_SCREEN_HANDLER_TYPE, (AutoCrafterGuiDescription gui, PlayerInventory inventory, Text title) -> new AutoCrafterScreen(gui, inventory.player, title));

```
[The crash](https://gitlab.com/snippets/1991214)

Note that my blockentity doesn't override `createMenu` because it already extends `LootableContainerBlockEntity`

For all I know my generic specification isn't even the problem. It looks like `createMenu` is calling itself for infinite recursion, but I'm using a vanilla implementation of `createMenu`. 

Sorry I'm basically asking for support in an issue at this point, is there a better place, maybe a dedicated discord server?

**Comment by Juuxel** [comment]
Yeah, there's the [Cotton discord server](https://discord.gg/9M5sACm) where you can ask questions. If you extend `LootableContainerBlockEntity`, you should instead make `createScreenHandler` construct a GUI description object:
```java
@Override
protected ScreenHandler createScreenHandler(int syncId, PlayerInventory playerInventory) {
    return new AutoCrafterGuiDescription(/* parameters here */);
}
```

**Comment by supersaiyansubtlety** [comment]
Ok thanks, I'll go ask there.
